version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: electron-12
  ignore:
  - dependency-name: electron
    versions:
    - 11.2.2
    - 12.0.0
    - 12.0.1
    - 12.0.2
    - 12.0.4
    - 12.0.5
  - dependency-name: electron-log
    versions:
    - 4.3.3
    - 4.3.4
  - dependency-name: electron-updater
    versions:
    - 4.3.8
  - dependency-name: electron-builder
    versions:
    - 22.10.5
